### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by kevingy** [seanmcelroy/McNNTP#1]
Are there any plans for a .NET Standard (or .NET Core) version of this library?

**Comment by seanmcelroy** [comment]
Hi there.  I don't really have plans to do this, although I don't perceive it would be especially hard to do.  Out of curiosity, what is your use case for the library?

**Comment by kevingy** [comment]
I want to develop an NNTP client application to do some statistical analysis. I'd like to use .NET Standard so that I can run the application in a Linux docker container and spin up as many instances as needed to reduce processing time. The analysis would involve almost entirely downloading headers from a newsgroup, storing select data, and when the headers are done downloading, run the analysis. Occasionally, based on the analysis, a body will be downloaded.

Does that sound like something that the client library can handle? Based on code inspection, it looks like it can, but the client code looks kinda sparse. If so, unless I find something else, I can consider doing the .NET Standard conversion.

**Comment by seanmcelroy** [comment]
Sure thing.  I converted the core client portion into a new subdirectory called "dotnet-core", where you can find an updated library and example client Program.cs.  It's what I could come up with quickly in a few hours, so it lacks robust unit testing... but does work against some testing of public NNTP servers I tried.  Let me know if that helps you out!

**Comment by kevingy** [comment]
The good news is that the library appears to work in a .NET Core application. My current issue is that the library does not appear to support user authentication, meaning I can't connect to the server with a username and password.

If I made mods, would you accept pull request(s)?

**Comment by seanmcelroy** [comment]
Glad to hear it -- and yes, I'd take any PR's, and would build some tests around it too.  Originally the project was the server protocol implementation and a client only complete enough to test that, but if you start submitting PR's for the client, I'll flesh it out too.

**Comment by seanmcelroy** [comment]
Hi @kevingy -- I took a few hours to separate the client into a new repo so it's cleaner to track.  Please submit PR's against: https://github.com/seanmcelroy/nntp-client

I also had to change the licensing from MIT to MS-PL to resolve a clean compilation issue related to the use of some of the Zlib code.
